### ISSUE TITLE
It might be better to use tags as your lab milestones

### ISSUE THREAD

**Issue by YuMS** [zyearn/6.828-labs#1]
Since `lab1` is your default branch, https://github.com/zyearn/6.828-labs presents your work at an early stage (just finished lab1). Plus it's hard to find where you implemented the rest labs, it may confuse others about whether you have finished all the labs.

I actually found your branches until I saw https://github.com/zyearn/6.828-labs/blob/lab6/LabNotes was on a different branch.

Since every of your branches includes its preceding branch, I suggest you to rename `lab6` back to `master`, remove `lab1`-`lab5`, and tag every branch's latest commit as `lab*`.

**Comment by zyearn** [comment]
@YuMS good suggestions, thks.

The reason why there are 6 branches in my project is because these branches are also in the original repository of 6.828. I just keep it unchanged :)

**Comment by YuMS** [comment]
Cool. And another simpler solution is to change default branch to `lab6`, which I believe is just a GitHub side setting without influencing your repo structure.
